import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { NextFooter } from "@/components/Shared/NextFooter";
import { ThemeProvider } from "@/components/context/ThemeContext";
import ThemeProviderLayout from "@/components/Theme/ThemeProviderLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  

  return (
    <html lang="en" data-theme={"#ffff"} cz-shortcut-listen="true">
       
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ThemeProvider>
          <ThemeProviderLayout>
          <div className="mx-auto">
            <div className="min-h-screen ">
              <AntdRegistry>{children}</AntdRegistry>
            </div>
            <NextFooter />
          </div>
          </ThemeProviderLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
